name: Push to branch

on:
  push:
    branches: [ "*" ]
  pull_request:

jobs:
  # ----------------------------------------------------------------------------------------------
  # CODE QUALITY ASSURANCE
  # ----------------------------------------------------------------------------------------------
  code_quality_assurance:
    name: Code Quality Assurance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          enable-cache: true
      - name: Run Ruff Style and Linting Checks
        run: |
          uv run ruff check
          uv run ruff format --check

      - name: Run ty Static Type Check
        run: uv run ty check
